# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180709_1632'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='org',
        ),
        migrations.DeleteModel(
            name='CityDict',
        ),
        migrations.DeleteModel(
            name='CourseOrg',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
