# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 23:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_userquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='answer_time',
            field=models.IntegerField(default=0, verbose_name='用时'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='答题时间'),
        ),
    ]
