# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_userquestioncom_userquestionfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionfav',
            name='is_fav',
            field=models.BooleanField(default=True, verbose_name='是否收藏'),
        ),
        migrations.AlterField(
            model_name='userquestionfav',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='答题时间'),
        ),
    ]
