# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-03 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20180703_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionfav',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='question.Question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='userquestionfav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
    ]
