# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20180703_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAsk',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='答题时间'),
        ),
        migrations.AlterField(
            model_name='userquestioncom',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='答题时间'),
        ),
        migrations.DeleteModel(
            name='CourseComments',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
