# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-04 19:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0036_question_difficulty'),
        ('operation', '0010_auto_20180727_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('type', models.CharField(choices=[('homework', '作业'), ('exam', '测试')], default='homework', max_length=10, verbose_name='试卷类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('limit_time', models.DateTimeField(default=datetime.datetime(2018, 8, 4, 19, 17, 11, 88685), verbose_name='截止时间')),
                ('status', models.CharField(choices=[('wait', '未发布'), ('finish', '已发布'), ('timeout', '已截止')], default='wait', max_length=10, verbose_name='状态')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='question.Question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.AddField(
            model_name='usertestreport',
            name='paper',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operation.UserPaper', verbose_name='试卷'),
            preserve_default=False,
        ),
    ]
