# Generated by Django 2.0 on 2018-08-05 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20180804_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaper',
            name='limit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 19, 28, 20, 727772), verbose_name='截止时间'),
        ),
    ]
