# Generated by Django 2.0 on 2018-08-08 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_auto_20180808_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaper',
            name='classes',
        ),
        migrations.AlterField(
            model_name='userpaper',
            name='limit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 15, 3, 7, 410378), verbose_name='截止时间'),
        ),
    ]
