# Generated by Django 2.0 on 2018-08-08 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180805_1928'),
        ('operation', '0015_auto_20180808_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaper',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='users.Classes', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='userpaper',
            name='limit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止时间'),
        ),
    ]
