# Generated by Django 2.0 on 2018-08-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180805_1928'),
        ('operation', '0016_auto_20180808_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='练习时间')),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Classes', verbose_name='班级')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.UserPaper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '班级报告',
                'verbose_name_plural': '班级报告',
            },
        ),
        migrations.AddField(
            model_name='usertestreport',
            name='class_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.ClassTestReport', verbose_name='班级报告'),
        ),
    ]
