# Generated by Django 2.0 on 2018-09-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0019_auto_20180913_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmessage',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
