# Generated by Django 2.0 on 2018-09-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0037_auto_20180805_1928'),
        ('operation', '0020_auto_20180913_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('class_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.ClassTestReport', verbose_name='班级报告')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
            },
        ),
        migrations.AlterModelOptions(
            name='usertestreport',
            options={'verbose_name': '学生报告', 'verbose_name_plural': '学生报告'},
        ),
        migrations.AddField(
            model_name='userquestion',
            name='question_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.QuestionReport', verbose_name='题目报告'),
        ),
    ]
