# Generated by Django 2.0 on 2018-09-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_auto_20180914_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreport',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operation.UserPaper', verbose_name='试卷'),
            preserve_default=False,
        ),
    ]
