# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 12:48
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', DjangoUeditor.models.UEditorField(default='', verbose_name='题目')),
                ('solve_step', models.TextField(default='', verbose_name='解答步骤')),
                ('like', models.IntegerField(default=0, verbose_name='赞')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '解题',
                'verbose_name_plural': '解题',
            },
        ),
    ]
