# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 00:38
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_solve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', DjangoUeditor.models.UEditorField(default='', verbose_name='题目')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='步骤序号')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '步骤',
                'verbose_name_plural': '步骤',
            },
        ),
        migrations.RemoveField(
            model_name='solve',
            name='solve_step',
        ),
        migrations.AlterField(
            model_name='solve',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='solve',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='step',
            name='solve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Solve', verbose_name='解题思路'),
        ),
    ]
