# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 20:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('teacher', '做家教'), ('student', '找家教')], default='student', max_length=10, verbose_name='发布类型')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('content', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='内容')),
                ('name', models.CharField(default='', max_length=10, verbose_name='联系人')),
                ('QQ', models.CharField(blank=True, max_length=13, null=True, verbose_name='QQ')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '家教信息',
                'verbose_name_plural': '家教信息',
            },
        ),
        migrations.RemoveField(
            model_name='publish',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
