# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180227_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='grade',
            field=models.CharField(choices=[('0', '学前'), ('1', '小学'), ('2', '初一'), ('3', '初二'), ('4', '初三'), ('5', '高一'), ('6', '高二'), ('7', '高三'), ('8', '其他')], default='0', max_length=2, verbose_name='年级'),
        ),
    ]
