# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180227_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.CharField(default='', max_length=100, verbose_name='科目'),
        ),
    ]
