# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180709_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='是否学生'),
        ),
    ]
