# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180727_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='school',
            field=models.CharField(default='', max_length=20, verbose_name='学校/机构'),
        ),
    ]
