# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 15:42
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180306_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wrong',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='问题'),
        ),
    ]
