# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='0', max_length=5, verbose_name='编号')),
                ('name', models.CharField(default='学前', max_length=5, verbose_name='年级')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='1', max_length=5, verbose_name='编号')),
                ('name', models.CharField(default='语文', max_length=5, verbose_name='学科')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='0', max_length=5, verbose_name='编号')),
                ('name', models.CharField(default='选择题', max_length=5, verbose_name='题目类型')),
            ],
            options={
                'verbose_name': '题目类型',
                'verbose_name_plural': '题目类型',
            },
        ),
    ]
