# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20180306_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='knowledge',
            field=models.CharField(default='', max_length=100, verbose_name='知识点'),
        ),
    ]
