# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_question_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=5, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='num',
            field=models.CharField(max_length=5, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.IntegerField(verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=5, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='num',
            field=models.CharField(max_length=5, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=5, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='type',
            name='num',
            field=models.CharField(max_length=5, verbose_name='编号'),
        ),
    ]
