# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20180308_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='type',
            name='id',
        ),
        migrations.AlterField(
            model_name='grade',
            name='num',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='num',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='type',
            name='num',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
