# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20180308_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Grade', verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Subject', verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Type', verbose_name='类型'),
        ),
    ]
