# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20180308_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='analysis',
            field=models.TextField(blank=True, default='', null=True, verbose_name='解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default='', verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='', verbose_name='问题'),
        ),
    ]
