# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20180308_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('num', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=5, verbose_name='知识点名称')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
            },
        ),
    ]
