# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20180327_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='section',
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
