# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20180327_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='知识点名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='节名称')),
                ('chapter', models.CharField(max_length=50, verbose_name='章名称')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.AddField(
            model_name='knowledge',
            name='section',
            field=models.ManyToManyField(blank=True, null=True, to='question.Section', verbose_name='章节信息'),
        ),
    ]
