# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20180327_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='section',
            field=models.ManyToManyField(default='', to='question.Section', verbose_name='章节信息'),
        ),
    ]
