# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20180327_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='question',
            name='knowledge',
            field=models.ManyToManyField(default='', to='question.Knowledge', verbose_name='知识点'),
        ),
    ]
