# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_auto_20180327_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='book',
            field=models.CharField(default='', max_length=50, verbose_name='书册名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='chapter_num',
            field=models.IntegerField(default=0, verbose_name='章编号'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_num',
            field=models.IntegerField(default=0, verbose_name='节编号'),
        ),
    ]
