# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_auto_20180327_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='section',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='section',
            field=models.CharField(default='', max_length=5),
        ),
    ]
