# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_auto_20180327_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_num', models.IntegerField(default=0, verbose_name='课编号')),
                ('lesson', models.CharField(max_length=50, verbose_name='课名称')),
                ('section_num', models.IntegerField(default=0, verbose_name='节编号')),
                ('section', models.CharField(max_length=50, verbose_name='节名称')),
                ('chapter_num', models.IntegerField(default=0, verbose_name='章编号')),
                ('chapter', models.CharField(max_length=50, verbose_name='章名称')),
                ('book', models.CharField(max_length=50, verbose_name='书册名称')),
            ],
            options={
                'verbose_name': '章节课',
                'verbose_name_plural': '章节课',
            },
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
