# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0021_auto_20180327_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='section',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='lesson',
            field=models.ManyToManyField(default='', to='question.Lesson', verbose_name='章节课信息'),
        ),
    ]
