# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0022_auto_20180327_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='question.Subject', verbose_name='科目'),
        ),
    ]
