# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-03 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0023_lesson_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教材名称')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='章编号')),
                ('name', models.CharField(max_length=50, verbose_name='章名称')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Book', verbose_name='教材')),
            ],
            options={
                'verbose_name': '章',
                'verbose_name_plural': '章',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='版本名称')),
                ('publishing_house', models.CharField(max_length=20, verbose_name='出版社')),
                ('publication_date', models.DateField(default=datetime.date(2018, 4, 3), verbose_name='出版时间')),
            ],
            options={
                'verbose_name': '教材版本',
                'verbose_name_plural': '教材版本',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='节编号')),
                ('name', models.CharField(max_length=50, verbose_name='节名称')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Chapter', verbose_name='章')),
            ],
            options={
                'verbose_name': '节',
                'verbose_name_plural': '节',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Edition', verbose_name='教材版本'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Subject', verbose_name='科目'),
        ),
    ]
