# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0024_auto_20180403_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '课', 'verbose_name_plural': '课'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_num',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='book',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='chapter_num',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_num',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AlterField(
            model_name='edition',
            name='publication_date',
            field=models.DateField(default=datetime.date(2018, 4, 7), verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Section', verbose_name='节'),
        ),
    ]
