# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0025_auto_20180407_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.AlterField(
            model_name='edition',
            name='publication_date',
            field=models.DateField(default=datetime.date(2018, 4, 16), verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='name',
            field=models.CharField(max_length=50, verbose_name='知识点名称'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question.Category', verbose_name='类别'),
        ),
    ]
