# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-17 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0026_auto_20180416_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='publication_date',
            field=models.DateField(default=datetime.date(2018, 4, 17), verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='lesson',
            field=models.ManyToManyField(to='question.Lesson', verbose_name='章节课信息'),
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge',
            field=models.ManyToManyField(blank=True, default='', null=True, to='question.Knowledge', verbose_name='知识点'),
        ),
    ]
