# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0027_auto_20180417_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='content',
        ),
        migrations.AlterField(
            model_name='edition',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge',
            field=models.ManyToManyField(blank=True, default='', to='question.Knowledge', verbose_name='知识点'),
        ),
    ]
