# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0028_auto_20180420_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Category', verbose_name='类别'),
        ),
    ]
