# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0029_auto_20180422_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, default='', null=True, verbose_name='选项'),
        ),
    ]
