# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 14:21
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0030_auto_20180423_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='问题'),
        ),
    ]
