# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0032_auto_20180709_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
