# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0035_auto_20180715_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '基础巩固'), (2, '素质提升'), (3, '能力拔高')], default=1, verbose_name='难易度'),
        ),
    ]
