# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20180711_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
